<div class="image">
    <a class="large" target="_blank" href="/image/<?= $image->slug ?>/original.jpg">
        <img src="/image/<?= $image->slug ?>/large.jpg" />
        <?php if (!empty($_SESSION['user']) && (($image->user && $image->user->id == $_SESSION['user']->id) || in_array($_SESSION['user']->username, option('admin')))): ?>
        <div class="actions">
            <a class="btn" href="/edit/<?= $image->slug ?>">Modifier</a>
            <a class="btn delete" href="/delete/<?= $image->slug ?>">Supprimer</a>
        </div>
        <?php endif; ?>
    </a>
    <div class="meta">
        <i class="icon icon-eye-<?php if ($image->private): ?>close<?php else: ?>open<?php endif; ?>"></i> <?= $image->popularity ?> vues
        <?php if ($image->user): ?>
        &mdash;
        <i class="icon icon-user"></i> <a href="/user/<?= $image->user->username ?>">@<?= $image->user->username ?></a>
        <?php endif; ?>
        <?php if ($image->sharedTag): ?>
        &mdash;
        <i class="icon icon-tags"></i>
            <?php foreach ($image->sharedTag as $tag): ?>
            <a href="/tag/<?= $tag->label ?>">#<?= $tag->label ?></a>
            <?php endforeach; ?>
        <?php endif; ?>
        &mdash;
        <i class="icon icon-calendar"></i>
        <?= date(option('date_format'), strtotime($image->date)) ?>
    </div>
</div>

<div class="codes">
    <p>
        <label>Afficher l'image :</label>
        <input id="image" type="text" value="<?= option('host') ?>/image/<?= $image->slug ?>" disabled="disabled" />
        <button rel="zero-clipboard" data-clipboard-target="image"><i class="icon icon-copy"></i> Copier</button>
    </p>
    <p>
        <label>Accéder à l'image :</label>
        <input id="original" type="text" value="<?= option('host') ?>/image/<?= $image->slug ?>/original.jpg" disabled="disabled" />
        <button rel="zero-clipboard" data-clipboard-target="original"><i class="icon icon-copy"></i> Copier</button>
    </p>
    <p>
        <label>Insérer la miniature dans un forum :</label>
        <input id="forum_thumbnail" type="text" value="[url=<?= option('host') ?>/image/<?= $image->slug ?>][img]<?= option('host') ?>/image/<?= $image->slug ?>/small.jpg[/img][/url]" disabled="disabled" />
        <button rel="zero-clipboard" data-clipboard-target="forum_thumbnail"><i class="icon icon-copy"></i> Copier</button>
    </p>
    <p>
        <label>Insérer l'image dans un forum :</label>
        <input id="forum_image" type="text" value="[url=<?= option('host') ?>/image/<?= $image->slug ?>][img]<?= option('host') ?>/image/<?= $image->slug ?>/medium.jpg[/img][/url]" disabled="disabled" />
        <button rel="zero-clipboard" data-clipboard-target="forum_image"><i class="icon icon-copy"></i> Copier</button>
    </p>
</div>
