<div class="images">
    <?php foreach ($images as $image): ?>
    <div class="image">
        <a href="/image/<?= $image->slug ?>">
            <img src="/image/<?= $image->slug ?>/square.jpg" />
        </a>
    </div>
    <?php endforeach; ?>
</div>

<?php if (isset($stats)): ?>
<div class="meta">
    <?= $stats['image_count'] ?> images &mdash; <?= $stats['user_count'] ?> utilisateurs &mdash; <?= round($stats['image_size']/1024/1024/1024, 2) ?> Go
</div>
<?php endif; ?>
