<html>
    <head>
        <title>Pix | <?php if (!empty($title)): ?><?= $title ?><?php else: ?>H&eacute;bergement d'images<?php endif; ?></title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.12.0/build/cssreset/cssreset-min.css" />
        <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Grand+Hotel" />
        <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" />
        <link rel="stylesheet" type="text/css" href="/style.css?v=<?= option('version') ?>" />
        <link href="/favicon.png?v=<?= option('version') ?>" rel="icon" />
        <?php if (!empty($image)): ?>
        <meta name="twitter:card" content="photo" />
        <meta name="twitter:image:src" content="<?= option('host') ?>/image/<?= $image->slug ?>/medium.jpg" />
        <?php endif; ?>
    </head>
    <body>
        <a href="https://github.com/blat/pix"><img style="position: fixed; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png" alt="Fork me on GitHub"></a>
        <div class="wrapper">
            <div class="header">
                <div class="container">
                    <h1 class="brand"><a href="/"><img src="/logo.png?v=<?= option('version') ?>" /> Pix</a></h1>

                    <ul class="navbar">
                        <li><a class="btn" href="/upload"><i class="icon icon-cloud-upload"></i> Upload</a></li>
                        <li><a href="/explore">Explorer</a></li>
                        <?php if (!empty($_SESSION['user'])): ?>
                        <li><a href="/user/<?= $_SESSION['user']->username ?>">Mes images</a></li>
                        <li><a href="/logout">Déconnexion</a></li>
                        <?php else: ?>
                        <li><a href="/login">Connexion</a></li>
                        <li><a href="/register">Inscription</a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>

            <div class="content">
                <div class="container">
                    <?php foreach ($flash as $type => $message): ?>
                        <div class="alert <?= $type ?>"><?= $message ?></div>
                    <?php endforeach; ?>

                    <?php if (!empty($title)): ?>
                        <h2 class="title"><?= $title ?></h2>
                    <?php endif; ?>

                    <?= $content ?>

                    <div class="clearfix"></div>
                </div>
            </div>

            <div class="footer">
                <div class="container">
                    <p><a target="_blank" href="http://pix.blizzart.net/">Pix v2.1</a>. Built with <a target="_blank" href="http://limonade-php.github.io/">Limonade</a>, <a target="_blank" href="http://redbeanphp.com/">RedBean</a>, <a target="_blank" href="http://phpimageworkshop.com/">Image Workshop</a> and <a target="_blank" href="https://github.com/indyarmy/jQuery.awesomeCloud.plugin/">awesomeCloud</a>. Icon made by <a target="_blank" href="http://www.flaticon.com/free-icon/image-quadrate_3949" title="Adam Whitcroft">Adam Whitcroft</a>.</p>
                </div>
            </div>
        </div>
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/zeroclipboard/1.1.7/ZeroClipboard.min.js"></script>
        <script type="text/javascript" src="/jquery.awesomeCloud-0.2.min.js"></script>
        <script type="text/javascript" src="/app.js?v=<?= option('version') ?>"></script>
        <script type="text/javascript">
            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', '<?= option('google_analytics') ?>']);
            _gaq.push(['_trackPageview']);
            (function() {
                var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
            })();
        </script>
    </body>
</html>
